DEBUG 2025-05-25 21:38:55.509 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-25 21:38:55.509 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-25 21:38:55.509 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-25 21:38:55.509 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-25 21:38:55.509 UTC: 	 Executing command: 'submit'
DEBUG 2025-05-25 21:38:55.509 UTC: 	 Found CRAB cache file /home/psajdak/.crab3
ERROR 2025-05-25 21:38:55.509 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2025-05-25 21:38:55.509 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2025-05-25 21:38:55.513 UTC: 	 Log file is /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/test/crab.log
DEBUG 2025-05-26 19:24:45.155 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-05-26 19:24:45.155 UTC: 	 Running on: Linux pcwaw09 5.14.0-503.23.2.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 12 05:52:18 EST 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-05-26 19:24:45.155 UTC: 	 Using SINGULARITY image: el9:x86_64
DEBUG 2025-05-26 19:24:45.155 UTC: 	 Operating System: AlmaLinux 9.5 (Teal Serval)
DEBUG 2025-05-26 19:24:45.155 UTC: 	 Executing command: 'status'
DEBUG 2025-05-26 19:24:45.155 UTC: 	 Found CRAB cache file /home/psajdak/.crab3
ERROR 2025-05-26 19:24:45.157 UTC: 	 Error: Jpsi_K/crab_full0_corrName is not a valid CRAB project directory.
ERROR 2025-05-26 19:24:45.157 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: Jpsi_K/crab_full0_corrName is not a valid CRAB project directory.
INFO 2025-05-26 19:24:45.159 UTC: 	 Log file is /eos/home-p/psajdak/CMSSW_14_2_2/src/UserCode/Analysis/test/crab.log
